run:
  build-tags:
    - goLayouter
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 5m

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  # vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - proto

  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.generated\\.go"

linters:
  enable-all: true
  disable:
    - goimports
    - golint
    - varcheck
    - structcheck
    - maligned
    - prealloc
    - unused
    - interfacer

  deadcode:
    skip-unreachable: true

  dupl:
    threshold: 100


  gocyclo:
    min-complexity: 10


  gosimple:
    min-confidence: 0


  govet:
    check-shadowing: false

  staticcheck:
    ignore:
      - ST1005
      - SA1019
      - SA4006
      - SA4008
      - SA5009
      - SA5010

  unconvert:
    ignore:
      - 'time.Duration'

  gosec:
    exclude:
      - 'G204'
      - 'G307'

  bodyclose:
    whitelist:
      - '*http.Request'
      - '*net.TCPConn'
      - '*tls.Conn'

  scopelint:
    check-parameter-shadowing: false
    check-shadowing-imported: false

  typecheck:
    unused-global-variables-exclude:
      - '.*_test\\.go'

  lll:
    line-length: 120
    tab-width: 2

  stylecheck:
    allow-underscore-dangle: true
    package-comments-first: false
    type-comments-first: false
    var-comments-first: false
    function-comments-first: false
    exported-first: true
    underscore-dangle-exempt-list: ['_', 'Err.*', 'Unmarshal.*']
    tag-char-case: 'lower'
    tag-struct-aligned: true
    tag-struct-lowercase: true
    tag-struct-camelcase: false
    tag-struct-uppercase: false
    tag-struct-omit-empty: true
    tag-json-lowercase: true
    tag-yaml-lowercase: true
    align-array-values: true
    align-case-conditions: true
    align-comments: true
    align-function-parameters: true
    align-struct-values: true
    break-return-assignment: true
    double-negation: true
    unnecessary-else: true
    unnecessary-first-var: true
    unnecessary-semicolon: true
    package-case: 'snake'
    package-underscore-exempt-list: ['test']
    receiver-name: 'r'
    receiver-name-exempt-list: ['srv', 'db', 'mux']
    short-if-assignment: true
    simplify-boolean-expr: true
    simplify-if-expr: true
    simplify-switch-expr: true
    space-after-cast: true
    trim-white-space: true
    unparam-name: 'unused'
    unparam-exempt-list: ['ctx', 'cancel', 'err']
    use-string-builder: true
    use-tab-indent: true
    var-group: 'aligned'
    var-indent: true